#ifndef __SYMBOLS_H__
#define __SYMBOLS_H__
#define END 0
#define INT 1
#define LONG 2
#define DOUBLE 3
#define SHORT 4
#define UNSIGNED 5
#define VOID 6
#define VOLATILE 7
#define WHILE 8
#define FLOAT 9
#define IF 10
#define ELSE 11
#define RETURN 12
#define CONSTANT 13
#define STRING_LITERAL 14
#define ASSIGN 15
#define ADD 16
#define SUBSTRACT 17
#define IDENTIFIER 18
#define END_OF_INSTRUCTION 19
#define AUTO 20
#define BREAK 21
#define CASE 22
#define CHAR 23
#define CONST 24
#define CONTINUE 25
#define DEFAULT 26
#define DO 27
#define ENUM 28
#define EXTERN 29
#define FOR 30
#define GOTO 31
#define REGISTER 32
#define SIGNED 33
#define SIZEOF 34
#define TYPEDEF 35
#define STRUCT 36
#define SWITCH 37
#define STATIC 38
#define ELLIPSIS 39
#define RIGHT_ASSIGN 40
#define LEFT_ASSIGN 41
#define ADD_ASSIGN 42
#define SUB_ASSIGN 43
#define MUL_ASSIGN 44
#define DIV_ASSIGN 45
#define MOD_ASSIGN 46
#define UNION 47
#define AND_ASSIGN 48
#define XOR_ASSIGN 49
#define OR_ASSIGN 50
#define RIGHT_OP 51
#define LEFT_OP 52
#define INC_OP 53
#define DEC_OP 54
#define PTR_OP 55
#define AND_OP 56
#define OR_OP 57
#define LE_OP 58
#define GE_OP 59
#define EQ_OP 60
#define NE_OP 61
#define LT_OP 62
#define GT_OP 63
#define CURLY_BR_OPEN 64
#define CURLY_BR_CLOSE 65
#define COMMA 66
#define COLON 67
#define ROUND_BR_OPEN 68
#define ROUND_BR_CLOSE 69
#define SQUARE_BR_OPEN 70
#define SQUARE_BR_CLOSE 71
#define DOT 72
#define AMPERSAND 73
#define EXCLAMATION_MARK 74
#define TILDA 75
#define MINUS 76
#define PLUS 77
#define STAR 78
#define SLASH 79
#define PERCENT 80
#define POWER 81
#define PIPE 82
#define QUESTION_MARK 83
#define COMM_MULTI_LINE 84
#define COMM_UNI_LINE 85
#define INLINE 86
#define RESTRICT 87
#define _BOOL 88
#define _COMPLEX 89
#define _IMAGINARY 90
#endif